// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $admin_images from "./routes/admin/images.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $admin_posts_slug_edit from "./routes/admin/posts/[slug]/edit.tsx";
import * as $admin_posts_new from "./routes/admin/posts/new.tsx";
import * as $admin_profile from "./routes/admin/profile.tsx";
import * as $api_posts_slug_ from "./routes/api/posts/[slug].ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $DeleteButton from "./islands/DeleteButton.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $ImageUploader from "./islands/ImageUploader.tsx";
import * as $Typewriter from "./islands/Typewriter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/admin/images.tsx": $admin_images,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/admin/posts/[slug]/edit.tsx": $admin_posts_slug_edit,
    "./routes/admin/posts/new.tsx": $admin_posts_new,
    "./routes/admin/profile.tsx": $admin_profile,
    "./routes/api/posts/[slug].ts": $api_posts_slug_,
    "./routes/api/upload.ts": $api_upload,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/DeleteButton.tsx": $DeleteButton,
    "./islands/Header.tsx": $Header,
    "./islands/ImageUploader.tsx": $ImageUploader,
    "./islands/Typewriter.tsx": $Typewriter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
